"use client";

import { useEffect, useState } from "react";
import type { MusicalEpisode } from "../data/musicalEpisodes";

export default function MusicalEpisodePanel({ episode }: { episode: MusicalEpisode }) {
  const storageKey=`relations:music:${episode.id}`;
  const [musicUrl,setMusicUrl]=useState("");const[generating,setGenerating]=useState(false);const[building,setBuilding]=useState(false);const[error,setError]=useState("");const[musicalUrl,setMusicalUrl]=useState("");
  useEffect(()=>{setMusicUrl(localStorage.getItem(storageKey)||"");},[storageKey]);
  async function generate(){setGenerating(true);setError("");try{const response=await fetch("/api/generate-episode-song",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({episodeId:episode.id,...episode.musical})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Song generation failed");setMusicUrl(data.url);localStorage.setItem(storageKey,data.url);}catch(e){setError(e instanceof Error?e.message:"Song generation failed");}finally{setGenerating(false);}}
  async function build(){setBuilding(true);setError("");try{const projectResponse=await fetch(`/api/project?episodeId=${encodeURIComponent(episode.id)}`,{cache:"no-store"});const project=await projectResponse.json();if(!projectResponse.ok)throw new Error(project.error||"Could not load episode");if(!project.finalUrl)throw new Error("Build the normal full episode first, then click Build Musical Final.");if(!musicUrl)throw new Error("Generate the episode song first.");const response=await fetch("/api/render-musical",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({episodeId:episode.id,videoUrl:project.finalUrl,musicUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Musical build failed");setMusicalUrl(data.url);}catch(e){setError(e instanceof Error?e.message:"Musical build failed");}finally{setBuilding(false);}}
  return <section style={{marginBottom:24,padding:20,border:"2px solid #111",borderRadius:18,background:"#fff8dc"}}><span className="eyebrow">SPECIAL MUSICAL EPISODE</span><h2 style={{margin:"8px 0"}}>Original Spider Song</h2><p>This episode uses an original MiniMax Music 3 comedy song instead of the normal Household Nonsense theme. Joe and Danda stay completely silent; the singer narrates the joke.</p><details><summary><b>Song lyrics</b></summary><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit"}}>{episode.musical.lyrics}</pre></details><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:14}}><button onClick={generate} disabled={generating}>{generating?"Generating song…":musicUrl?"Regenerate Episode Song":"Generate Episode Song"}</button><button onClick={build} disabled={building||!musicUrl}>{building?"Building musical final…":"Build Musical Final"}</button></div>{musicUrl&&<div style={{marginTop:14}}><audio src={musicUrl} controls style={{width:"100%"}}/><small>Song is saved permanently to R2. Regenerate if you want another musical take.</small></div>}{musicalUrl&&<div style={{marginTop:14}}><b>✓ Musical final ready</b><video src={musicalUrl} controls playsInline style={{width:"100%",maxHeight:520,marginTop:8}}/></div>}{error&&<p style={{marginTop:12}}><b>{error}</b></p>}</section>;
}
