"use client";
import { useEffect, useState } from "react";
import type { Episode } from "@/data/episodes";
import { narrationVoices, type Narration } from "@/lib/production";
export default function NarrationPanel({episode,onChange,onReady,household=false}:{episode:Episode;onChange:()=>void;onReady:(ready:boolean)=>void;household?:boolean}) {
  const [items,setItems]=useState<Record<number,Narration>>({});
  const [dirty,setDirty]=useState<Record<number,boolean>>({});
  const [voice,setVoice]=useState("onyx");
  const [loaded,setLoaded]=useState(false);
  const [busy,setBusy]=useState<number|null>(null);
  const [error,setError]=useState("");
  useEffect(()=>{let active=true;setLoaded(false);fetch(`/api/narration?episodeId=${encodeURIComponent(episode.id)}`).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!active)return;const initial:Record<number,Narration>={};const unsaved:Record<number,boolean>={};episode.scenes.forEach((scene,i)=>{initial[i]=d.scenes[i]||{text:scene.narration||"",voice:"onyx",url:"",duration:0};unsaved[i]=!d.scenes[i]&&Boolean(scene.narration);});setItems(initial);setDirty(unsaved);setVoice(Object.values(initial).find(x=>x.url)?.voice||"onyx");setLoaded(true);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[episode]);
  const ready=loaded&&busy===null&&!Object.values(dirty).some(Boolean)&&Object.values(items).every(x=>!x.text||Boolean(x.url));
  useEffect(()=>{onReady(ready);},[ready,onReady]);
  function edit(index:number,text:string){setItems(current=>({...current,[index]:{...current[index],text,url:"",duration:0}}));setDirty(current=>({...current,[index]:true}));onChange();}
  async function save(index:number,action:"save"|"generate"){
    setBusy(index);setError("");onChange();try{const item=items[index];const r=await fetch("/api/narration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({episodeId:episode.id,sceneIndex:index,text:item.text,voice:action==="generate"?voice:item.voice,action})});const d=await r.json();if(!r.ok)throw Error(d.error);setItems(current=>({...current,[index]:d.narration}));setDirty(current=>({...current,[index]:false}));}catch(e){setError(e instanceof Error?e.message:"Narration failed.");}finally{setBusy(null);}
  }
  return <div className="overlayEditor"><h3>{household?"Optional spoken voice":"Narration"}</h3><p>{household?"Add Joe’s spoken lines to the scenes you want voiced. The final export replaces those scenes’ generated audio with AI speech; other scenes keep their original audio. This adds sound to existing animation but does not animate Joe’s mouth.":"Each line starts with its scene. Studio pads the rest with silence and replaces generated scene audio in narrated exports."} Voices are AI-generated. Generate buttons use your OpenAI API credit; saving text is free.</p><label>{household?"Joe voice for the next generation":"Narrator voice for the next generation"}<select value={voice} disabled={!loaded||busy!==null} onChange={e=>setVoice(e.target.value)}>{narrationVoices.map(v=><option key={v} value={v}>{v}</option>)}</select></label><p>To change an existing voice, regenerate that scene's narration. Use the same voice for every scene to keep one narrator.</p>{episode.scenes.map((scene,index)=>{const item=items[index];return <div key={index}><label>Scene {index+1} {household?"spoken line":"narration"}<textarea disabled={!loaded||busy!==null} value={item?.text||""} maxLength={1000} onChange={e=>edit(index,e.target.value)}/></label><button disabled={!loaded||busy!==null} onClick={()=>void save(index,"save")}>Save text{!item?.text?" / no narration":""}</button>{" "}<button disabled={!loaded||busy!==null||!item?.text.trim()} onClick={()=>void save(index,"generate")}>{busy===index?"Working…":item?.url?"Regenerate narration (uses API credit)":"Generate narration (uses API credit)"}</button>{item?.url&&<div><audio controls src={item.url}/><p>{item.voice} · {item.duration.toFixed(1)} seconds · planned scene {scene.duration} seconds</p>{item.duration>scene.duration&&<p className="errorText">This line exceeds the planned scene duration. Shorten it or provide a longer video.</p>}</div>}{dirty[index]&&<p>Unsaved changes</p>}</div>;})}{error&&<p className="errorText" role="alert">{error}</p>}{!ready&&<p>Save each edited line and generate its audio before building the final video. Leave a line empty and save it for a silent scene.</p>}</div>;
}
